<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>76fdc4e5-6806-46e1-83f7-1b5cdeb540c0</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
		<DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
		<PackageReference Include="Marten" Version="9.16.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\NINJA.EShop.Shared\NINJA.EShop.Shared\NINJA.EShop.Shared.csproj" />
		<ProjectReference Include="..\..\NINJA.EShop.Shared\NINJA.EShop.Shared.Messaging\NINJA.EShop.Shared.Messaging.csproj" />
	</ItemGroup>
</Project>
