services:
  ninja.eshop.catalog.api:
    container_name: ninja.eshop.catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__MartenDb=Server=ninja.eshop.catalog.Db;Port=5432;Database=NinjaEShopCatalogDb;Username=postgres;Password=postgres;Include Error Detail=true
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/.aspnet/https:ro
    depends_on:
      - ninja.eshop.catalog.Db
     
  ninja.eshop.basket.api:
    container_name: ninja.eshop.basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__MartenDb=Server=ninja.eshop.basket.Db;Port=5432;Database=NinjaEShopBasketDb;Username=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=ninja.eshop.distibutedCache:6379
    ports:
      - "6001:8080"
      - "6061:8081"
    depends_on:
      - ninja.eshop.basket.Db
      - ninja.eshop.distibutedCache   
    volumes:
    - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    - ${APPDATA}/ASP.NET/Https:/home/.aspnet/https:ro

  ninja.eshop.catalog.Db:
    container_name: ninja.eshop.catalog.Db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NinjaEShopCatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  ninja.eshop.basket.Db:
    container_name: ninja.eshop.basket.Db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NinjaEShopBasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data

  ninja.eshop.distibutedCache:
    container_name: ninja.eshop.distibutedCache
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - ninja.eshop.catalog.Db
      - ninja.eshop.basket.Db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5055:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    depends_on:
      - ninja.eshop.distibutedCache
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
volumes:
  postgres_catalog:
  postgres_basket:
  pgadmin_data:
  redisinsight_data: