services:
  ninja.eshop.ordering.api:
    image: ${DOCKER_REGISTRY-}ninjaeshoporderingapi
    build:
      context: .
      dockerfile: src/NINJA.EShop.Ordering/NINJA.EShop.Ordering.API/Dockerfile
    depends_on:
      - ninja.eshop.ordering.Db
      - ninja.eshop.messagebroker

  ninja.eshop.catalog.api:
    image: ${DOCKER_REGISTRY-}ninjaeshopcatalogapi
    build:
      context: src
      dockerfile: NINJA.EShop.Catalog/NINJA.EShop.Catalog.API/Dockerfile
    depends_on:
      - ninja.eshop.catalog.Db
      - ninja.eshop.messagebroker
  ninja.eshop.basket.api:
    image: ${DOCKER_REGISTRY-}ninjaeshopbasketapi
    build:
      context: .
      dockerfile: src/NINJA.EShop.Basket/NINJA.EShop.Basket.API/Dockerfile
    depends_on:
      - ninja.eshop.basket.Db
      - ninja.eshop.messagebroker

  ninja.eshop.discount.grpc:
    image: ${DOCKER_REGISTRY-}ninjaeshopdiscountgrpc
    build:
      context: .
      dockerfile: src/NINJA.EShop.Discount/NINJA.EShop.Discount.Grpc/Dockerfile

  ninja.eshop.catalog.Db:
    image: postgres:16
    restart: always

  ninja.eshop.basket.Db:
    image: postgres:16
    restart: always

  ninja.eshop.distibutedCache:
    image: redis:8.8
    restart: always

  ninja.eshop.ordering.Db:
    image: mcr.microsoft.com/mssql/server
    restart: always

  ninja.eshop.messagebroker:
    image: rabbitmq:4.0-management
    restart: always

volumes:
  postgres_catalog:
  postgres_basket: