services:
  ninja.eshop.catalog.api:
    container_name: ninja.eshop.catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__MartenDb=Server=ninja.eshop.catalog.Db;Port=5432;Database=NinjaEShopCatalogDb;Username=postgres;Password=postgres;Include Error Detail=true
      - MessageBroker__Host=ninja.eshop.messagebroker
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/.aspnet/https:ro
    depends_on:
      - ninja.eshop.catalog.Db
      - ninja.eshop.messagebroker
     
  ninja.eshop.basket.api:
    container_name: ninja.eshop.basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__MartenDb=Server=ninja.eshop.basket.Db;Port=5432;Database=NinjaEShopBasketDb;Username=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=ninja.eshop.distibutedCache:6379
      - GrpcSettings__DiscountUrl=https://ninja.eshop.discount.grpc:8081
      - MessageBroker__Host=ninja.eshop.messagebroker
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6001:8080"
      - "6061:8081"
    depends_on:
      - ninja.eshop.basket.Db
      - ninja.eshop.distibutedCache
      - ninja.eshop.discount.grpc
      - ninja.eshop.messagebroker
    volumes:
    - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    - ${APPDATA}/ASP.NET/Https:/home/.aspnet/https:ro

  ninja.eshop.ordering.api:
    container_name: ninja.eshop.ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__OrderingDb=Server=ninja.eshop.ordering.Db;Database=NinjaEShopOrderingDb;User Id=sa;Password=Passw0rd123!;TrustServerCertificate=True;MultipleActiveResultSets=True
      - MessageBroker__Host=ninja.eshop.messagebroker
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    ports:
      - "6003:8080"
      - "6063:8081"
    depends_on:
      - ninja.eshop.ordering.Db
      - ninja.eshop.messagebroker
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


  ninja.eshop.discount.grpc:
    container_name: ninja.eshop.discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Data Source=NinjaEShopDiscountDb 
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  ninja.eshop.catalog.Db:
    container_name: ninja.eshop.catalog.Db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NinjaEShopCatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  ninja.eshop.basket.Db:
    container_name: ninja.eshop.basket.Db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NinjaEShopBasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data

  ninja.eshop.distibutedCache:
    container_name: ninja.eshop.distibutedCache
    restart: always
    ports:
      - "6379:6379"

  ninja.eshop.ordering.Db:
    container_name: ninja.eshop.ordering.Db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd123!
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  ninja.eshop.messagebroker:
    container_name: ninja.eshop.messagebroker
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - ninja.eshop.catalog.Db
      - ninja.eshop.basket.Db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5055:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    depends_on:
      - ninja.eshop.distibutedCache
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data

volumes:
  postgres_catalog:
  postgres_basket:
  sqlserver_data:
  pgadmin_data:
  redisinsight_data:
  rabbitmq_data: