<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>4ea7bea5-fc36-4a0f-be3d-b8ef83f5858a</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Protos\discount.proto" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\discount.proto" GrpcServices="Server" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\NINJA.EShop.Shared\NINJA.EShop.Shared\NINJA.EShop.Shared.csproj" />
	</ItemGroup>
</Project>
