<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>5856773b-2ce7-45ad-9bed-7e8da37f3a51</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Basket\CehckoutBasketEndpoint.cs" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Basket\CheckoutBasket\CheckoutBasketEndpoint.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.49.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Scrutor" Version="7.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
		<PackageReference Include="Marten" Version="9.16.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\NINJA.EShop.Shared\NINJA.EShop.Shared.Messaging\NINJA.EShop.Shared.Messaging.csproj" />
		<ProjectReference Include="..\..\NINJA.EShop.Shared\NINJA.EShop.Shared\NINJA.EShop.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Protobuf Include="..\..\NINJA.EShop.Discount\NINJA.EShop.Discount.Grpc\Protos\discount.proto" GrpcServices="Client">
	    <Link>Protos\discount.proto</Link>
	  </Protobuf>
	</ItemGroup>

</Project>
